"""
fetch_geometry.py — pre-fetch and persistently cache site geometry.

Run this once before opening windsite.html so the 3D scene loads
immediately without waiting for the Infrared API.

Usage:
    .venv/Scripts/python fetch_geometry.py

Output:
    cache/geometry_<hash>.json   — raw cache used by server.py
    site_data.js                 — window.SITE_DATA for offline use
"""

from __future__ import annotations
import json, math, os
from pathlib import Path
from datetime import datetime, timezone

# ── Site polygon — Barcelona Eixample (~330 m × 370 m, single tile) ──────────
# GeoJSON: [lon, lat], CCW, WGS84
POLYGON = {
    "type": "Polygon",
    "coordinates": [[
        [2.1600, 41.3900],
        [2.1640, 41.3900],
        [2.1640, 41.3937],
        [2.1600, 41.3937],
        [2.1600, 41.3900],
    ]],
}

HERE  = Path(__file__).parent
CACHE = HERE / "cache"
CACHE.mkdir(exist_ok=True)


def poly_hash(polygon: dict) -> str:
    import hashlib
    return hashlib.md5(json.dumps(polygon, sort_keys=True).encode()).hexdigest()[:12]


def mesh_to_dict(bid: str, mesh) -> dict | None:
    cs = list(mesh.coordinates)
    if not cs:
        return None
    xs, ys, zs = cs[0::3], cs[1::3], cs[2::3]
    h = round(max(zs) - min(zs), 2)
    if h < 2:
        return None
    return {
        "id":       bid,
        "height":   h,
        "cx":       round((min(xs) + max(xs)) / 2, 2),
        "cy":       round((min(ys) + max(ys)) / 2, 2),
        "minX":     round(min(xs), 2), "maxX": round(max(xs), 2),
        "minY":     round(min(ys), 2), "maxY": round(max(ys), 2),
        "vertices": cs,
        "indices":  list(mesh.indices),
    }


def tree_to_dict(tid: str, feat: dict, sw_lon: float, sw_lat: float) -> dict | None:
    g = feat.get("geometry") or {}
    if g.get("type") != "Point":
        return None
    lon, lat = g["coordinates"]
    p = feat.get("properties") or {}
    lon_m = 111_320 * math.cos(math.radians(sw_lat))
    return {
        "id": tid,
        "x":  round((lon - sw_lon) * lon_m, 2),
        "y":  round((lat - sw_lat) * 111_320, 2),
        "h":  float(p.get("height") or 8),
        "r":  float(p.get("crown_radius") or p.get("crownRadius") or 3),
    }


def main() -> None:
    key = os.getenv("INFRARED_API_KEY")
    if not key:
        raise SystemExit("❌  INFRARED_API_KEY is not set.\n"
                         "    Run:  set INFRARED_API_KEY=your-key  (cmd)\n"
                         "          $env:INFRARED_API_KEY='your-key'  (PowerShell)")

    h    = poly_hash(POLYGON)
    file = CACHE / f"geometry_{h}.json"

    if file.exists():
        data = json.loads(file.read_text())
        print(f"✅  Already cached: {len(data['buildings'])} buildings  "
              f"{len(data['trees'])} trees  [{h}]")
        print(f"   Delete {file} to force a re-fetch.")
        _write_js(data)
        return

    from infrared_sdk import InfraredClient

    coords = POLYGON["coordinates"][0]
    sw_lon = min(c[0] for c in coords)
    sw_lat = min(c[1] for c in coords)

    print("🔗  Connecting to Infrared …")
    with InfraredClient() as client:
        print("🏢  Fetching buildings …")
        area     = client.buildings.get_area(POLYGON)
        print("🌳  Fetching vegetation …")
        area_veg = client.vegetation.get_area(POLYGON)

    buildings = [b for bid, m in area.buildings.items()
                 if (b := mesh_to_dict(bid, m))]
    trees     = [t for tid, f in area_veg.features.items()
                 if (t := tree_to_dict(tid, f, sw_lon, sw_lat))]

    print(f"   ✓ {len(buildings)} buildings · {len(trees)} trees")

    data = {
        "polygon":    POLYGON,
        "swLon":      sw_lon,
        "swLat":      sw_lat,
        "buildings":  buildings,
        "trees":      trees,
        "fetchedAt":  datetime.now(timezone.utc).isoformat(),
    }

    file.write_text(json.dumps(data))
    print(f"💾  {file}")

    _write_js(data)
    print("✅  Done — start server.py or open windsite.html directly")


def _write_js(data: dict) -> None:
    """Write site_data.js so windsite.html works without the server."""
    js = HERE / "site_data.js"
    fetched = data.get("fetchedAt", "unknown")
    nb = len(data.get("buildings", []))
    nt = len(data.get("trees", []))
    js.write_text(
        f"// Auto-generated by fetch_geometry.py\n"
        f"// {fetched}  ·  {nb} buildings  ·  {nt} trees\n"
        f"// Re-run fetch_geometry.py to refresh\n"
        f"window.SITE_DATA={json.dumps(data, separators=(',', ':'))};\n"
    )
    print(f"💾  {js}")


if __name__ == "__main__":
    main()
